-- workflow=hdfs_to_ftp_test
--  period=1440
--  loadType=incremental
--  logDrivenType=timewindow

-- step=1
-- source=hdfs
--  configPrefix=dw
--  fileNamePattern=()(dw_card_3m_event_.+\.gz)()
-- target=ftp
--  configPrefix=dw
--  fileDir=/hairui/output/dw
-- writeMode=overwrite
