codecov:
  bot: "codecov-io"
  status:
    project:
      default:
        target: auto
        threshold: 0.5%
        base: auto
        if_ci_failed: ignore
        informational: true
        only_pulls: false
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: yes
  require_head: yes
github_checks: true
coverage:
  status:
    patch: true
ignore:
  - "**/datasource/**"
  - "*Config"
  - "*Exception"
  - "*Accessor"
