-- workflow=dynamic_transformer
--  period=1440
--  loadType=incremental
--  logDrivenType=timewindow

-- step=1
-- source=transformation
--  className=com.github.sharpdata.sharpetl.spark.end2end.TestDynamicLoadingTransformer
--  methodName=transform
--  transformerType=dynamic_object
-- target=temp
--  tableName=`dynamic_tmp_transformer_result_table`