version: '3'
services:
  hive:
    image: metorikku/hive:2.3.7
    ports:
      - "9083:9083"
      - "10000:10000"
      - "10002:10002"
    environment:
      - CONNECTION_URL=jdbc:mysql://mysql:3306/hive?useSSL=false
      - CONNECTION_USER_NAME=root
      - CONNECTION_PASSWORD=root
      - WAREHOUSE_DIR=file://${HOME}/Documents/warehouse
      - WAIT_HOSTS=mysql:3306
    depends_on:
      - mysql
    volumes:
      - ${HOME}/Documents/warehouse:${HOME}/Documents/warehouse
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ${PWD}/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root