-- workflow=batch_kafka_test
--  period=1440
--  loadType=incremental
--  logDrivenType=timewindow

-- step=1
-- source=batch_kafka
--  topics=test
--  groupId=0
--  schemaDDL=`id` STRING,`name` STRING
-- target=console
