name: release

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env: [
          '-PscalaVersion=2.11 -PsparkVersion=2.3.2 -PscalaCompt=2.11.12',
          '-PscalaVersion=2.11 -PsparkVersion=2.4.8 -PscalaCompt=2.11.12',
          '-PscalaVersion=2.12 -PsparkVersion=2.4.8 -PscalaCompt=2.12.15',
          '-PscalaVersion=2.12 -PsparkVersion=3.0.3 -PscalaCompt=2.12.15',
          '-PscalaVersion=2.12 -PsparkVersion=3.1.2 -PscalaCompt=2.12.15',
          '-PscalaVersion=2.12 -PsparkVersion=3.2.0 -PscalaCompt=2.12.15',
          '-PscalaVersion=2.13 -PsparkVersion=3.2.0 -PscalaCompt=2.13.7',
          '-PscalaVersion=2.12 -PsparkVersion=3.3.0 -PscalaCompt=2.12.15',
          '-PscalaVersion=2.13 -PsparkVersion=3.3.0 -PscalaCompt=2.13.7',
        ]
    steps:
      - uses: actions/checkout@v2

      - name: setup env variable
        run: |
          echo "ENV=${{ matrix.env }}" >> $GITHUB_ENV

      - name: setup test container reuse
        run: |
          echo 'testcontainers.reuse.enable=true' >> ~/.testcontainers.properties

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Style Check
        run: ./gradlew scalastyleMainCheck ${{ matrix.env }}

      - name: Test
        run: ./gradlew test aggregateScoverage ${{ matrix.env }}

      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          directory: ./build/reports/scoverage/
          verbose: true

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: spark/build/libs/*.jar